// <auto-generated />
using DevDeck.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevDeck.Web.Migrations
{
    [DbContext(typeof(DevDeckDbContext))]
    [Migration("20260601094109_AddExternalInstanceMode")]
    partial class AddExternalInstanceMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DevDeck.Web.Data.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.DevService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExternalPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartArguments")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StopArguments")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopCommand")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseExternalInstance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DevServices");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.LaunchProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LaunchProfiles");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.LaunchProfileService", b =>
                {
                    b.Property<int>("LaunchProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("LaunchProfileId", "DevServiceId");

                    b.HasIndex("DevServiceId");

                    b.ToTable("LaunchProfileServices");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.ProxyRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorizationPolicy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStartService")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationUrlOverride")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DevServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchHostsCsv")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathPrefixToAdd")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathPrefixToRemove")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathSet")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathTransformMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreserveHostHeader")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireHealthyDestination")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowOnDashboard")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DevServiceId");

                    b.HasIndex("MatchPath");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProxyRoutes");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.ServiceEnvironmentVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DevServiceId", "Key")
                        .IsUnique();

                    b.ToTable("ServiceEnvironmentVariables");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.ServiceHealthCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastCheckedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DevServiceId");

                    b.ToTable("ServiceHealthChecks");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.ServiceRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartArgumentsSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartCommandSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("StoppedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectorySnapshot")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DevServiceId", "StartedUtc");

                    b.ToTable("ServiceRuns");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.LaunchProfileService", b =>
                {
                    b.HasOne("DevDeck.Web.Data.Entities.DevService", "DevService")
                        .WithMany()
                        .HasForeignKey("DevServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevDeck.Web.Data.Entities.LaunchProfile", "LaunchProfile")
                        .WithMany("Services")
                        .HasForeignKey("LaunchProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevService");

                    b.Navigation("LaunchProfile");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.ProxyRoute", b =>
                {
                    b.HasOne("DevDeck.Web.Data.Entities.DevService", "DevService")
                        .WithMany("ProxyRoutes")
                        .HasForeignKey("DevServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DevService");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.ServiceEnvironmentVariable", b =>
                {
                    b.HasOne("DevDeck.Web.Data.Entities.DevService", "DevService")
                        .WithMany("EnvironmentVariables")
                        .HasForeignKey("DevServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevService");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.ServiceHealthCheck", b =>
                {
                    b.HasOne("DevDeck.Web.Data.Entities.DevService", "DevService")
                        .WithMany("HealthChecks")
                        .HasForeignKey("DevServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevService");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.ServiceRun", b =>
                {
                    b.HasOne("DevDeck.Web.Data.Entities.DevService", "DevService")
                        .WithMany("Runs")
                        .HasForeignKey("DevServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevService");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.DevService", b =>
                {
                    b.Navigation("EnvironmentVariables");

                    b.Navigation("HealthChecks");

                    b.Navigation("ProxyRoutes");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("DevDeck.Web.Data.Entities.LaunchProfile", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
